.github/workflows/build-container.yaml
=> CI testing

.github/workflows/build-container.yaml
Added minor changes in ci workflow
=> Added changes in ci workflow

.github/workflows/build-container.yaml
Added minor changes in ci workflow
=> Added minor changes in ci workflow and removed some matrix

.github/workflows/build-container.yaml
=> Added changes in ci workflows

src/apps/console/components/commons.tsx, src/apps/console/routes/_.$account.$cluster.nodepools/nodepool-resources.tsx
=> Fixed status issue in nodepool

src/apps/console/components/commons.tsx
=> Fixed minor ui issues

src/apps/devdoc/style.css
=> Devdoc background image url experiment

src/apps/console/routes/_.$account.$cluster.settings.general/route.tsx
Fixed wrong url redirection on cluster delete
=> Fixed wrong url redirection on cluster delete

src/apps/devdoc/app/layout/theme.tsx, src/apps/devdoc/app/utils/config.tsx, src/apps/devdoc/app/utils/use-config.tsx, src/apps/devdoc/pages/_meta.json, src/apps/devdoc/pages/index.mdx
=> Website design changes

src/apps/devdoc/app/layout/theme.tsx, src/apps/devdoc/app/utils/config.tsx, src/apps/devdoc/app/utils/use-config.tsx
=> Website prettier fixes

src/apps/devdoc/app/components/header-secondary.tsx, src/apps/devdoc/app/components/header.tsx, src/apps/devdoc/app/components/page/index.tsx, src/apps/devdoc/app/components/search.tsx, src/apps/devdoc/app/components/sidebar.tsx, src/apps/devdoc/app/components/toc.tsx, src/apps/devdoc/app/layout/theme.tsx, src/apps/devdoc/app/utils/config.tsx
- Fixed ui bugs and updated text descriptions
=> Fixed website bugs

.github/workflows/build-container.yaml, src/apps/console/page-components/new-scope.tsx
Please provide a brief summary of the changes. If it's a bug fix, describe the bug and how the changes fix it. If it's a new feature or enhancement, explain the motivation and context behind the changes.
Fixes # (issue)
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
**Test Configuration**:
* OS:
* Version:
* Kubernetes Version:
* Kubernetes Distribution:
=> remove namesapce from env creation

Taskfile.yaml, src/apps/console/page-components/app-states.tsx, src/apps/console/routes/_main+/$account+/$project+/$environment+/app+/$app+/settings+/compute/route.tsx, src/apps/console/routes/_main+/$account+/$project+/$environment+/new-app/app-compute.tsx, src/apps/console/routes/_main+/$account+/$project+/$environment+/new-app/app-review.tsx, src/apps/console/server/r-utils/key-constants.js
Resolves kloudlite/kloudlite/issues/45
=> KLO-118 : Add repo name and image tag while creating and updating app 

fake-data-generator/gen.ts, src/apps/console/routes/_main+/$account+/repo+/$repo+/buildruns/route.tsx, src/apps/console/routes/_main+/$account+/repo+/$repo+/builds/_index.tsx, src/apps/console/routes/_main+/$account+/repo+/$repo+/images/route.tsx
implements skeltons for below screens:
- images
- build integrations
- build runs
=> adds skelton implementation for packages

src/apps/console/page-components/app-states.tsx, src/apps/console/routes/_main+/$account+/packages+/repos/repo-resources.tsx, src/apps/console/routes/_main+/$account+/repo+/$repo+/_layout.tsx, src/apps/console/routes/_main+/$account+/repo+/$repo+/images/route.tsx
Resolves kloudlite/kloudlite#49
=> KLO-175 : Fix/redirect repo page

package.json, pnpm-lock.yaml, src/apps/console/routes/_main+/$account+/$project+/$environment+/new-app/app-compute.tsx
=> Fixed select not showing value issue

lib/client/helpers/socket/context.tsx, lib/client/helpers/socket/useWatch.tsx, src/apps/console/page-components/config-resource.tsx, src/apps/console/page-components/secret-resource.tsx, src/apps/console/routes/_main+/$account+/$project+/$environment+/apps/apps-resources.tsx, src/apps/console/routes/_main+/$account+/$project+/$environment+/managed-resources/managed-resources-resource.tsx, src/apps/console/routes/_main+/$account+/$project+/$environment+/new-app/app-compute.tsx, src/apps/console/routes/_main+/$account+/$project+/$environment+/new-app/app-review.tsx, src/apps/console/routes/_main+/$account+/$project+/$environment+/routers/router-resources.tsx, src/apps/console/routes/_main+/$account+/$project+/environments/resources.tsx, src/apps/console/routes/_main+/$account+/$project+/managed-services/backend-services-resources.tsx, src/apps/console/routes/_main+/$account+/infra+/$cluster+/helm-charts/helm-chart-resources.tsx, src/apps/console/routes/_main+/$account+/infra+/$cluster+/nodepools/nodepool-resources.tsx, src/apps/console/routes/_main+/$account+/infra+/$cluster+/settings+/domain/domain-resources.tsx, src/apps/console/routes/_main+/$account+/infra+/$cluster+/storage/storage-resources.tsx, src/apps/console/routes/_main+/$account+/infra+/clusters/cluster-resources.tsx, src/apps/console/routes/_main+/$account+/projects/project-resources.tsx, src/apps/console/routes/_main+/$account+/repo+/$repo+/builds/build-resources.tsx, src/apps/console/server/r-utils/key-constants.js
Resolves kloudlite/kloudlite#56
=> KLO-104 : Needs to implement auto reload on resource change event.

package.json, pnpm-lock.yaml, src/apps/console/routes/_main+/$account+/$project+/$environment+/app+/$app+/settings+/_layout.tsx, src/apps/console/routes/_main+/$account+/$project+/$environment+/app+/$app+/settings+/compute/route.tsx, src/apps/console/routes/_main+/$account+/$project+/$environment+/app+/$app+/settings+/scaling/route.tsx, src/apps/console/routes/_main+/$account+/$project+/$environment+/new-app/app-compute.tsx, src/apps/console/routes/_main+/$account+/$project+/$environment+/new-app/app-review.tsx, src/apps/console/routes/_main+/$account+/$project+/$environment+/routers/handle-router.tsx, src/apps/console/routes/_main+/$account+/$project+/$environment+/routers/router-resources.tsx, src/generated/gql/sdl.graphql
Resolves kloudlite/kloudlite#57
=> KLO-153: Impl/autoscaling apps

src/apps/console/routes/_main+/$account+/user-profile/_index.tsx, src/apps/console/routes/_main+/$account+/user-profile/_layout.tsx, src/apps/console/routes/_main+/$account+/user-profile/account/route.tsx, src/apps/console/routes/_main+/$account+/user-profile/login-connections/route.tsx, src/apps/console/routes/_main+/$account+/user-profile/notifications/route.tsx, src/apps/console/routes/_main+/_layout/_layout.tsx, src/design-system/components/molecule/profile.tsx
Resolves kloudlite/kloudlite#58
=> KLO-196: user profile page is now a seperate full screen page.

src/apps/console/routes/_main+/$account+/infra+/$cluster+/helm-charts/_index.tsx, src/apps/console/routes/_main+/$account+/settings+/user-management/handle-user.tsx, src/apps/console/routes/_main+/$account+/settings+/user-management/route.tsx, src/apps/console/routes/_main+/$account+/settings+/user-management/user-access-resource.tsx, src/apps/console/server/gql/queries/router-queries.ts
Resolves kloudlite/kloudlite#63
=> KLO-222 : update role name to displayname

src/apps/console/page-components/new-project.tsx, src/apps/console/routes/_a+/onboarding+/$a+/$cluster+/new-project.tsx, src/apps/console/routes/_main+/$account+/$project+/$environment+/new-app/app-compute.tsx, src/apps/console/routes/_main+/$account+/$project+/$environment+/new-app/app-review.tsx, src/apps/console/routes/_main+/$account+/infra+/_layout.tsx, src/apps/console/routes/_main+/$account+/infra+/clusters/route.tsx, src/apps/console/routes/_main+/$account+/infra+/vms.tsx
Resolved kloudlite/kloudlite#69
- add image pull policy of app in advanced options
- change project review page as per figma
- removes vms from infra and make cluster tab flat
=> KLO-178 && KLO-240 : Project Creation page should match design in figma && remove vm-instance from infra

src/apps/console/routes/_main+/$account+/infra+/$cluster+/helm-charts/handle-helm-chart.tsx, src/apps/console/routes/_main+/$account+/infra+/$cluster+/storage/storage-resources-v2.tsx
=> remove extra button for bound storage

gql-queries-generator/doc/queries.graphql, src/apps/console/components/multi-step-progress-wrapper.tsx, src/apps/console/routes/_main+/$account+/$project+/env+/$environment+/new-app/app-config-mount.tsx, src/apps/console/routes/_main+/$account+/$project+/env+/$environment+/new-app/app-dialogs.tsx, src/apps/console/routes/_main+/$account+/$project+/env+/$environment+/new-app/app-environment-variables.tsx, src/apps/console/routes/_main+/$account+/$project+/env+/$environment+/new-app/route.tsx, src/apps/console/server/gql/queries/secret-queries.ts, src/generated/gql/server.ts
Resolves kloudlite/kloudlite#76
- adds managed resource as environment in create app and in setting of app
- minor ui redesign of app environment
=> KLO-250 : Add mres as config and secret in environment of app

gql-queries-generator/doc/queries.graphql, src/apps/console/routes/_main+/$account+/repo+/$repo+/_layout.tsx, src/apps/console/routes/_main+/$account+/repo+/$repo+/build+/$build+/buildruns/buildruns-resources.tsx, src/apps/console/routes/_main+/$account+/repo+/$repo+/build+/$build+/buildruns/route.tsx, src/apps/console/server/gql/queries/build-run-queries.ts, src/generated/gql/sdl.graphql, src/generated/gql/server.ts
- fixed issue with build run page, to match with api.
=> :bug: Fixed issue with build run page.

lib/client/components/logger/index.tsx, lib/client/components/logger/log-select.tsx, src/apps/console/routes/_main+/$account+/$project+/env+/$environment+/app+/$app+/logs-n-metrics/route.tsx, src/apps/console/routes/_main+/$account+/$project+/msvc+/$msv+/logs-n-metrics/route.tsx
- added filter by pods on logs.
=> :sparkles: Added filter by podname on logs

src/apps/console/routes/_main+/$account+/$project+/environments/environment-resources-v2.tsx, src/generated/gql/sdl.graphql
resolves kloudlite/kloudlite#84
=> KLO-259: public private env badge implementated

src/apps/console/routes/_main+/$account+/user-profile/login-connections/route.tsx
resolves kloudlite/kloudlite#85
=> KLO-260: Refactoring/login connection

gql-queries-generator/doc/queries.graphql, src/apps/console/page-components/new-cluster.tsx, src/apps/console/routes/_main+/$account+/settings+/cloud-providers/handle-provider.tsx, src/apps/console/routes/_main+/$account+/settings+/cloud-providers/provider-resources-v2.tsx, src/apps/console/server/gql/queries/cluster-queries.ts, src/apps/console/server/gql/queries/provider-secret-queries.ts, src/apps/console/utils/commons.tsx, src/generated/gql/sdl.graphql, src/generated/gql/server.ts
Resolves kloudlite/kloudlite#92
=> KLO-269 : WEB: Add GCP integration for cluster and cloud provider

src/apps/console/components/common-console-components.tsx, src/apps/console/components/console-list-components.tsx, src/apps/console/routes/_main+/$account+/env+/$environment+/_layout.tsx, src/apps/console/routes/_main+/$account+/env+/$environment+/apps/apps-resources-v2.tsx, src/apps/console/routes/_main+/$account+/env+/$environment+/apps/handle-intercept.tsx, src/apps/console/routes/_main+/$account+/infra+/clusters/cluster-resources-v2.tsx, src/apps/console/routes/_main+/$account+/infra+/vpn-devices/vpn-resources-v2.tsx, src/apps/iot-console/routes/_main+/$account+/$project+/deviceblueprint+/$deviceblueprint+/apps/app-resource.tsx
=> ui changes for app, device and cluster

src/apps/console/routes/_a+/new-team.tsx, src/apps/console/routes/_a+/onboarding+/$a+/attach-new-cluster.tsx, src/apps/console/routes/_a+/onboarding+/$a+/new-cloud-provider.tsx, src/apps/console/routes/_main+/$account+/infra+/clusters/route.tsx
Resolves kloudlite/kloudlite#227
=> WEB: Remove cloudprovider and cluster creation step with attached cluster for smooth onboarding

src/apps/console/routes/_main+/$account+/env+/$environment+/_layout.tsx, src/apps/console/routes/_main+/$account+/managed-services/backend-services-resources-V2.tsx, src/apps/console/routes/_main+/$account+/msvc+/$msv+/_layout.tsx, src/apps/console/routes/_main+/$account+/msvc+/$msv+/index.tsx, src/apps/console/routes/_main+/$account+/msvc+/$msv+/managed-resources/handle-managed-resource.tsx, src/apps/console/routes/_main+/$account+/msvc+/$msv+/managed-resources/managed-resources-resource-v2.tsx, src/apps/console/routes/_main+/$account+/msvc+/$msv+/managed-resources/route.tsx, src/apps/console/routes/_main+/$account+/msvc+/$msv+/managed-resources/tools.tsx, src/apps/console/routes/_main+/$account+/msvc+/$msv+/new-managed-resource/_index.tsx
Resolves kloudlite/kloudlite#228
=> WEB: Implementation of managed resoure to be moved inside managed service
